spring.application.name=ATS-score-checker

server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.com.atschecker=DEBUG
logging.level.org.springframework.web=INFO
